/**
 * In dieser Datei sind alle guiIdentifiers gelistet
 */
#ifndef _GUI_IDENTIFIERS_H
#define _GUI_IDENTIFIERS_H


#define GUI_ID_PANEL 1
#define GUI_ID_STATUS_BAR 2

#define GUI_ID_MUSIC_PUSH_BUTTON 101

#define GUI_ID_ADD_BUILDING_PUSH_BUTTON_BASE 111
#define GUI_ID_ADD_BUILDING_PUSH_BUTTON_CRAFTSMAN GUI_ID_ADD_BUILDING_PUSH_BUTTON_BASE
#define GUI_ID_ADD_BUILDING_PUSH_BUTTON_FARM (GUI_ID_ADD_BUILDING_PUSH_BUTTON_BASE+1)
#define GUI_ID_ADD_BUILDING_PUSH_BUTTON_PORT (GUI_ID_ADD_BUILDING_PUSH_BUTTON_BASE+2)
#define GUI_ID_ADD_BUILDING_PUSH_BUTTON_PUBLIC (GUI_ID_ADD_BUILDING_PUSH_BUTTON_BASE+3)

#define GUI_ID_PANEL_SWITCH_PUSH_BUTTON_BASE 201
#define GUI_ID_PANEL_SWITCH_PUSH_BUTTON_BUILD GUI_ID_PANEL_SWITCH_PUSH_BUTTON_BASE
#define GUI_ID_PANEL_SWITCH_PUSH_BUTTON_2 (GUI_ID_PANEL_SWITCH_PUSH_BUTTON_BASE+1)
#define GUI_ID_PANEL_SWITCH_PUSH_BUTTON_3 (GUI_ID_PANEL_SWITCH_PUSH_BUTTON_BASE+2)
#define GUI_ID_PANEL_SWITCH_PUSH_BUTTON_4 (GUI_ID_PANEL_SWITCH_PUSH_BUTTON_BASE+3)

#define GUI_ID_PANEL_SWITCH_BASE 206
#define GUI_ID_PANEL_SWITCH_BUILD GUI_ID_PANEL_SWITCH_BASE
#define GUI_ID_PANEL_SWITCH_2 (GUI_ID_PANEL_SWITCH_BASE+1)
#define GUI_ID_PANEL_SWITCH_3 (GUI_ID_PANEL_SWITCH_BASE+2)
#define GUI_ID_PANEL_SWITCH_4 (GUI_ID_PANEL_SWITCH_BASE+3)

#define GUI_ID_TEST_BUTTON1 301
#define GUI_ID_TEST_BUTTON2 302
#define GUI_ID_TEST_PUSH_BUTTON 311


#endif
